Pkalsh
biforest/java-calculator pull request #3
Opened 2021-02-25 16:40 UTC by pkalsh

간단한 프로그램인데 힘드네요..

2021-02-27 06:58 UTC, oereo reviewed
oereo code review

2021-02-27 06:58 UTC, oereo commented on README.md
> +        String[] values = value.split(" ");
공백을 추가하신 이유는 무엇인가요???

2021-02-27 06:58 UTC, oereo commented on src/main/java/ui/printer/ConsolePrinter.java
> +    private final String GREET_MESSAGE = "계산기 프로그램입니다.\n" +
현재 java 에서 Multiline에 대한 기능을 제공을 안해주는 상황인 것 같아요.
Adrian Walker의 @Multiline 라이브러리가 있는 것 같은데 필요성이 있다면 사용하셔도 괜찮을 것 같아요!

ex)
```suggestion
/**
계산기 프로그램입니다.
숫자와 사칙연산 기호를 공백으로 구분하여 입력해주세요.
프로그램을 종료하시려면 exit을 입력해주세요
*/
@Multiline String GREET_MESSAGE;
```

2021-02-27 06:58 UTC, oereo commented on src/main/java/CalculatorApplication.java
> +    private Optional<Integer> calculateExpression(String expression) {
개인적인 궁금사항입니다
optional 을 사용하신 이유가 직접적으로 nulll check에 대한 부분때문에 사용하신 것 같습니다
optional 이 함수형 언어에서 따온 문법이라고 하는데 객체지향적으로 코드를 짠다고 했을 때 optional을 사용하는게 단순 null check를 할 때와 차이가 궁금합니다.

결론 : 동민님이 이 코드 부분에서 optional를 사용하신 이유가 궁금합니다

2021-02-27 06:58 UTC, oereo commented on src/main/java/domain/calculator/ExpressionValidator.java
> +    }
라인간격을 한줄씩 띄는 것으로 통일해도 좋을 것 같습니다
맥 기준 : option + command + L 을 하면 자동적으로 정렬 및 포맷을 맞추어 줍니다.

2021-02-27 06:58 UTC, oereo commented on src/main/java/domain/calculator/Parser.java
> +import java.util.*;
`import java.util.stream.Collectors` 하나의 라이브러리를 사용하고 있는 상황이라면 넣지 않아도 될 것 같습니다

2021-02-27 07:34 UTC, pkalsh commented on README.md
> +        String[] values = value.split(" ");
글쎄요 .. 그냥 오타난거 같은데 원래 그런게 아니었나봐요?

2021-02-27 07:45 UTC, pkalsh commented on src/main/java/CalculatorApplication.java
> +    private Optional<Integer> calculateExpression(String expression) {
이펙티브 자바에 실린 내용을 그냥 전적으로 따랐는데요.
아이템 55에 나와있는 내용입니다.

> 자바 8 전에는 메서드가 특정 조건에서 값을 반환할 수 없을 때 취할 수 있는 선택지가 두 가지 있었다.
> 예외를 던지거나, (반환 타입이 객체 참조라면) null을 반환하는 것이다.
> 두 방법 모두 허점이 있다. 예외는 진짜 예외적인 상황에서만 사용해야 하며 예외를 생성할 때 스택 추적 전체를
> 캡처하므로 비용도 만만치 않다.
> null을 반환하면 이런 문제가 생기지 않지만, 그 나름의 문제가 있다. null을 반환할 수 있는 메서드를 호출할 때는,
> 별도의 null 처리 코드를 추가해야 한다. null 처리를 무시하고 반환된 null 값을 어딘가에 저장해두면 언젠가 
> NullPointerException이 발생할 수 있다. 그것도 근본적인 원인, 즉 null을 반환하게 한 실제 원인과는 전혀 상관없는
> 코드에서 말이다.

저자가 이런 이유로 null 반환을 꺼려하고 그 대안으로 Optional 반환을 소개하고 있어요. 물론 제 코드에 적용되는 부분은 없어 보이지만 책 내용을 따라 null 반환을 의도적으로 안하려는 습관을 들이려고 Optional을 택했습니다. 😃

2021-02-27 07:49 UTC, pkalsh commented on src/main/java/domain/calculator/ExpressionValidator.java
> +    }
정렬했습니다!

2021-02-27 07:51 UTC, pkalsh commented on src/main/java/domain/calculator/Parser.java
> +import java.util.*;
java.util.* 임포트 구문은 LinkedList와 Queue, List, Arrays를 끌어다 쓰는 과정에 인텔리제이에서 자동으로 임포트해준 것으로 보입니다

2021-02-27 07:59 UTC, pkalsh commented on src/main/java/ui/printer/ConsolePrinter.java
> +    private final String GREET_MESSAGE = "계산기 프로그램입니다.\n" +
보기 안좋았는데 그런 라이브러리가 있었군요!
한번 적용해보겠습니다 😄

2021-02-28 05:33 UTC, kouz95 requested changes
고생하셨습니다 🙂
추상클래스와 인터페이스, Optional등 자바의 다양한 기술들을 활용하셨네요. 때문인지 많은 학습을 하고 있다는게 느껴졌습니다. 열정 👍

지금은 학습에 더 중점이 있기 때문에 자유롭게 시도해보는것에 반대하지는 않습니다. 저 또한 그런 성향이 강했고, 그로 인해 많이 성장했다고 생각하기 때문에 오히려 반갑습니다.

다만, 학습이 아닌 엔지니어로서의 역할을 하게 될땐, 오버엔지니어링과 그로 인한 생산성이 떨어지는것에 대해 경계해야 됩니다.

[오버엔지니어링과 언더엔지니어링의 경계](https://huns.me/posts/2019-09-26-overengineering-vs-underengineering)

- Printer와 Receiver를 인터페이스로 만든 이유가 있나요?
- 확장성을 고려하다 가독성이나 유지보수성이 낮아지진 않았나요?

> "Scalable" 이란 단어는 소프트웨어 엔지니어의 마음에 신비롭고 깜짝 놀라게 하는 힘이 있음. 살짝 입밖에 내는 것만으로 그들을 타락한 광란에 빠져들게 함. 이 단어를 사용함으로써 무자비한 행동들이 정당화 됨
>
> [(번역) 업계에서 6년 있은 뒤, 마음이 바뀐 소프트웨어 개발 토픽들](https://news.hada.io/topic?id=3635)

2021-02-28 05:33 UTC, kouz95 commented on src/main/java/CalculatorApplication.java
> +    private Calculator calculator;
final을 추가해주어 재할당을 막아줘도 좋을것 같아요.

```suggestion
    private final Printer printer;
    private final Receiver receiver;
    private final Calculator calculator;
```

2021-02-28 05:33 UTC, kouz95 commented on src/main/java/CalculatorApplication.java
> +        Integer result;
int가 아닌 Integer를 사용한 이유가 있나요?
primitive 와 wrapper type의 차이는 어떤것이 있을까요?

2021-02-28 05:33 UTC, kouz95 commented on src/main/java/CalculatorApplication.java
> +        }
예외에 대한 처리가 같으니 묶을수도 있겠군요!

```suggestion
        } catch (DivideByZeroException | InvalidInputException e) {
            System.out.println(e.getMessage());
            return Optional.empty();
        }
```

2021-02-28 05:33 UTC, kouz95 commented on src/main/java/CalculatorApplication.java
> +        }
return을 try안에 넣으면 result를 미리 선언해둘 필요는 없을것 같아요!
```suggestion
        try {
            int result = calculator.calculate(expression);
            return Optional.of(result);
        } catch (DivideByZeroException | InvalidInputException e) {
            System.out.println(e.getMessage());
            return Optional.empty();
        }
```

2021-02-28 05:33 UTC, kouz95 commented on src/main/java/domain/calculator/exception/InvalidInputException.java
> +    }
아래와 같이 사용해도 의도한 바와 동일하게 동작할것 같네요 🙂

```suggestion

    public InvalidInputException(String message) {
        super(message);
    }
```

2021-02-28 05:33 UTC, kouz95 commented on src/main/java/domain/expression/operator/Operator.java
> +        return new Division();
`+`, `-`, `*` 가 아닌것은 무조건 나누기라고 생각할 수 있을까요?

2021-02-28 05:33 UTC, kouz95 commented on src/main/java/domain/calculator/Calculator.java
> +public class Calculator {
Calculator 객체를 만든 의도는 무엇이었나요?

2021-02-28 05:33 UTC, kouz95 commented on src/main/java/ui/printer/ConsolePrinter.java
> +    private final String EXIT_MESSAGE = "프로그램을 종료합니다.";
상수는 `private static final` !

2021-02-28 05:33 UTC, kouz95 commented on src/test/java/CalculatorTest.java
> +        assertThatExceptionOfType(InvalidInputException.class)
assertThatExceptionOfType() 👍

2021-02-28 05:33 UTC, kouz95 commented on src/main/java/domain/calculator/ExpressionValidator.java
> +        for (int i = 1; i < tokenList.size(); i += 2) {
1, 2와 같은 숫자를 상수로 포장하여 의미를 담을 수 있지 않을까요?

2021-03-21 07:30 UTC, pkalsh commented on src/main/java/CalculatorApplication.java
> +        Integer result;
Optional에서 객체만을 제네릭으로 받을 수 있어 통일하겠다고 쓴거긴 합니다.
기능면에서 큰 차이는 없으니 혼동을 피하기 위해서는 int로 쓰는게 조금 더 낫다고 생각합니다.

2021-03-21 07:33 UTC, pkalsh commented on src/main/java/domain/expression/operator/Operator.java
> +        return new Division();
연산 이전에 입력 문자열을 정규 표현식으로 미리 검증하는 로직이 있어 예외 처리할 수 있다고 생각했습니다.
이런 경우에도 꼭 예외 처리를 하는게 낫나요?

2021-03-21 07:53 UTC, pkalsh commented on src/main/java/domain/calculator/Calculator.java
> +public class Calculator {
계산만 전문적으로 하는 객체를 의도했습니다.
CalculatorApplication은 어플리케이션 실행 순서만 담당하도록 의도했기 때문에 분리하는 선택을 했습니다.

2021-03-22 12:13 UTC, kouz95 approved these changes
Enum과 추상클래스 둘 다 시도해 보셨네요 👍

추가적으로 적용해 볼 수 있는 것에 대해 간단한 리뷰 남겼으니 확인해주세요!

이외에도 `ExpressionValidator`의 로직이 꽤나 복잡해 보이는데, `Integer.parseInt()` 나 `Operation`의 생성 과정 중에서 대부분의 예외처리가 이루어지고 있지 않을까? 라는 생각도 들어요.
작은 클래스들을 많이 만들고, 클래스의 생성 과정에서 유효성 검사를 진행한다면 Validator와 같은 클래스에 의존하지 않고도 스스로 안전한 객체임을 보장할 수 있을거에요 🙂

요구사항은 충분히 만족한것 같아 Approve 하겠습니다 👏
고생하셨습니다!

2021-03-22 12:13 UTC, kouz95 commented on src/main/java/CalculatorApplication.java
> +            return Optional.of(result);
```suggestion
            return Optional.of(calculator.calculate(expression));
```
도 충분할 것 같습니다 🙂

2021-03-22 12:13 UTC, kouz95 commented on src/main/java/domain/expression/Expression.java
> +    private Operator operator;
```suggestion
    private final int left;
    private final int right;
    private final Operator operator;
```
Expression을 불변 객체로 만들 수도 있겠네요 🙂

2021-03-22 12:13 UTC, merged